### ISSUE TITLE
为什么detectors在wheat数据集上只比frcnn r50好一点呢

### ISSUE THREAD

**Issue by CarryHJR** [WangLibo1995/mmdetection-v2-with-mosaic-data-augmentation#1]
https://www.kaggle.com/pestipeti/pytorch-starter-fasterrcnn-inference 这个frcnn r50 线上67
看您的detectors 报68，感觉不应该啊

**Comment by WangLibo1995** [comment]
DetetoRS我没调参数的，默认设置跑的，数据增强这些都没有，跑起来太慢了。。，模型很大



---原始邮件---
发件人: "CarryHJR"<notifications@github.com&gt;
发送时间: 2020年7月14日(周二) 晚上8:51
收件人: "WangLibo1995/mmdetection-v2-with-mosaic-data-augmentation"<mmdetection-v2-with-mosaic-data-augmentation@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [WangLibo1995/mmdetection-v2-with-mosaic-data-augmentation] 为什么detectors在wheat数据集上只比frcnn r50好一点呢 (#1)




 
https://www.kaggle.com/pestipeti/pytorch-starter-fasterrcnn-inference 这个frcnn r50 线上67
 看您的detectors 报68，感觉不应该啊

**Comment by CarryHJR** [comment]
明白，我看https://www.kaggle.com/pestipeti/pytorch-starter-fasterrcnn-train 这个作者的设置也是只有flip，不过他是40epoch，和1/255的归一化

**Comment by CarryHJR** [comment]
我看到您也有评论 Good job! But I get a LB score 0.64 using your code,my epoch is 30.Do you add other training strategies to get a LB score 0.6687?
这个的后续您复现成功了，我自己跑的cascade r50 12 epoch也只有63.58

**Comment by WangLibo1995** [comment]
我觉得比赛数据量还是小了点，撑不起太大的模型



---原始邮件---
发件人: "CarryHJR"<notifications@github.com&gt;
发送时间: 2020年7月14日(周二) 晚上11:09
收件人: "WangLibo1995/mmdetection-v2-with-mosaic-data-augmentation"<mmdetection-v2-with-mosaic-data-augmentation@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Libo Wang"<574961738@qq.com&gt;;
主题: Re: [WangLibo1995/mmdetection-v2-with-mosaic-data-augmentation] 为什么detectors在wheat数据集上只比frcnn r50好一点呢 (#1)




 
明白，我看https://www.kaggle.com/pestipeti/pytorch-starter-fasterrcnn-train 这个作者的设置也是只有flip，不过他是40epoch，和1/255的归一化

**Comment by CarryHJR** [comment]
同whu 我是遥感国重的

**Comment by WangLibo1995** [comment]
邮箱是我QQ，加QQ聊吧



---原始邮件---
发件人: "CarryHJR"<notifications@github.com&gt;
发送时间: 2020年7月14日(周二) 晚上11:12
收件人: "WangLibo1995/mmdetection-v2-with-mosaic-data-augmentation"<mmdetection-v2-with-mosaic-data-augmentation@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Libo Wang"<574961738@qq.com&gt;;
主题: Re: [WangLibo1995/mmdetection-v2-with-mosaic-data-augmentation] 为什么detectors在wheat数据集上只比frcnn r50好一点呢 (#1)




 
同whu 我是遥感国重的
