### ISSUE TITLE
About Wheat compete

### ISSUE THREAD

**Issue by ChristopherSTAN** [WangLibo1995/mmdetection-v2-with-mosaic-data-augmentation#2]
Hi, Libo

I have star your great repo.

What CV mAP when you get your LB ?

I found I can easily achieve:
![image](https://user-images.githubusercontent.com/7379039/89092674-d4a44a00-d381-11ea-8ace-488e6a920d38.png)

BTW, we can chat in Chinese.

**Comment by WangLibo1995** [comment]
mmdet的模型效果都不理想，gfl 69.9，cascadercnn+resnest 71 而且都加了Mosaic数据增强，提升效果不明显



---Original---

**Comment by ChristopherSTAN** [comment]
我在fold0 的val set能到mAP0.93，这和训练yolov5的时候差不多了，请问你的呢

**Comment by WangLibo1995** [comment]
我的也差不多，我的ap small最好的能到0.20，但线上结果依旧很低



---Original---

**Comment by ChristopherSTAN** [comment]
哎，还是yolov5牛逼
